import React, { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { apiClient } from '@/services/apiClient';
import { Github, GitPullRequest, Loader2, CheckCircle } from 'lucide-react';

const GitHubPRPanel = ({ githubContext, optimizedCode, disabled }) => {
  const [isCommitting, setIsCommitting] = useState(false);
  const [success, setSuccess] = useState(false);
  const [prUrl, setPrUrl] = useState('');
  const [error, setError] = useState('');
  const [title, setTitle] = useState('AI Code Optimizer: suggested improvements');

  if (!githubContext) return null;

  const handleCommit = async () => {
    if (disabled || !optimizedCode) return;
    setIsCommitting(true);
    setError('');
    try {
      const payload = {
        file_path: githubContext.path,
        content: optimizedCode,
        title: title,
        body: `This PR was automatically generated by AI Code Optimizer.\n\nOptimized file: \`${githubContext.path}\``
      };

      const [owner, repo] = githubContext.repo.split('/');
      const res = await apiClient.githubApplyPatch(owner, repo, payload);

      if (res.pull_request?.html_url) {
        setPrUrl(res.pull_request.html_url);
        setSuccess(true);
      }
    } catch (err) {
      console.error('GitHub PR failed:', err);
      setError(err.message || 'Failed to create PR');
    } finally {
      setIsCommitting(false);
    }
  };

  return (
    <div className="mt-4 p-4 rounded-xl bg-[var(--surface-1)] border border-[var(--card-border)] shadow-sm">
      <div className="flex items-center gap-2 mb-3">
        <Github className="w-4 h-4 text-[var(--fg-color)]" />
        <h4 className="text-sm font-semibold text-[var(--fg-color)]">GitHub Automation</h4>
      </div>

      <p className="text-xs text-muted mb-3">
        Imported from: <span className="font-mono bg-[var(--card-bg)] px-1 rounded">{githubContext.repo}</span>
      </p>

      {success ? (
        <motion.div
          initial={{ opacity: 0, y: 5 }}
          animate={{ opacity: 1, y: 0 }}
          className="p-3 bg-emerald-500/10 border border-emerald-500/30 rounded-lg flex flex-col items-center gap-2"
        >
          <CheckCircle className="w-6 h-6 text-emerald-400" />
          <p className="text-xs text-emerald-300 text-center font-medium">Successfully opened Pull Request!</p>
          <a
            href={prUrl}
            target="_blank"
            rel="noopener noreferrer"
            className="mt-1 text-xs font-bold text-emerald-400 hover:text-emerald-300 underline underline-offset-2 flex items-center gap-1"
          >
            View PR on GitHub
          </a>
        </motion.div>
      ) : (
        <div className="space-y-3">
          <input
            type="text"
            value={title}
            onChange={(e) => setTitle(e.target.value)}
            disabled={isCommitting || disabled}
            placeholder="PR Title..."
            className="w-full text-xs px-3 py-2 rounded bg-[var(--card-bg)] border border-[var(--card-border)] text-[var(--fg-color)] focus:border-indigo-500 outline-none"
          />
          <button
            onClick={handleCommit}
            disabled={disabled || isCommitting || !optimizedCode}
            className="w-full flex items-center justify-center gap-2 py-2 px-4 rounded-lg bg-indigo-600 hover:bg-indigo-500 text-white text-sm font-medium transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
          >
            {isCommitting ? (
              <Loader2 className="w-4 h-4 animate-spin" />
            ) : (
              <GitPullRequest className="w-4 h-4" />
            )}
            {isCommitting ? 'Creating PR...' : 'Commit & Create PR'}
          </button>
        </div>
      )}

      <AnimatePresence>
        {error && (
          <motion.div
            initial={{ opacity: 0, height: 0 }}
            animate={{ opacity: 1, height: 'auto' }}
            exit={{ opacity: 0, height: 0 }}
            className="mt-3 p-2 bg-red-500/10 border border-red-500/30 rounded text-xs text-red-400"
          >
            {error}
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
};

export default GitHubPRPanel;

